// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "followFocusPrimary": boolean;
      "syncEnabled": boolean;
      "splitTabsTitle": string;
      "primaryScrollbarR": number;
      "primaryScrollbarG": number;
      "primaryScrollbarB": number;
    };
  }
}
